version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app 
    environment:
      - CHOKIDAR_USEPOLLING=true    
  api:
    build: ./api
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./api:/app  
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: '3306'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: time_db   
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql 
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'  
    environment:
      - PMA_ARBITRARY=1          
volumes:
  mysql_data:      